import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#FF6600',
        secondary: '#D93E40',
        'secondary-alt': '#F1352A',
        tertiary: '#1a1a1a',
        'heading-color': '#222222',
        'body-color': '#444444',
        gray: '#65676B',
        midgray: '#878787',
        light: '#E4E6EA',
        lighter: '#CED0D4',
        lightest: '#F5F5F5',
        border: '#E6E6E6',
        white: '#ffffff',
        success: '#3EB75E',
        danger: '#FF0003',
        warning: '#FF8F3C',
        info: '#FF8533',
        facebook: '#3B5997',
        twitter: '#1BA1F2',
        youtube: '#ED4141',
        linkedin: '#0077B5',
        pinterest: '#E60022',
        instagram: '#C231A1',
        vimeo: '#FF6600',
        twitch: '#6441A3',
        discord: '#7289da',
        'extra01': '#666666',
        'extra02': '#606770',
        'extra03': '#FBFBFD',
        'extra04': '#1A1A1A',
        'extra05': '#242424',
      },
      fontFamily: {
        primary: ['var(--font-primary)', 'DIN-Black', 'sans-serif'],
        secondary: ['var(--secondary-font)', 'DIN-Black', 'sans-serif'],
        heading: ['var(--font-heading)', 'DIN-Black', 'sans-serif'],
        body: ['var(--font-body)', 'DIN-Black', 'sans-serif'],
        'din-black': ['DIN-Black', 'sans-serif'],
        'din-alternate': ['DIN-Alternate', 'sans-serif'],
      },
      fontSize: {
        'h1': '44px',
        'h2': '36px',
        'h3': '30px',
        'h4': '24px',
        'h5': '18px',
        'h6': '16px',
        'b1': '18px',
        'b2': '16px',
        'b3': '14px',
        'b4': '12px',
      },
      lineHeight: {
        'h1': '1.2',
        'h2': '1.2',
        'h3': '1.2',
        'h4': '1.2',
        'h5': '1.2',
        'h6': '1.2',
        'b1': '1.67',
        'b2': '1.5',
        'b3': '1.6',
        'b4': '1.3',
      },
      borderRadius: {
        'radius': '10px',
        'radius-big': '16px',
        'radius-small': '6px',
      },
      boxShadow: {
        'primary': '0px 4px 10px rgba(37, 47, 63, 0.1)',
        'light': '0 2px 6px 0 rgba(0, 0, 0, 0.05)',
        'dark': '0 2px 6px 0 rgba(0, 0, 0, 0.2)',
      },
      transitionDuration: {
        'DEFAULT': '0.3s',
      },
      spacing: {
        '15': '15px',
      },
    },
  },
  plugins: [],
};

export default config;
